source(here::here("code/build/build1.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/00_analysis_flowchart_fig1.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/01_analysis_table1.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/01b_analyse_missingness.R"));rm(list=ls()); source(here::here("../../.Rprofile")) # NEEDS TO BE RERUN
source(here::here("code/analysis/02_analyse_incidencerates.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/03_analyse_cuminc.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/04_analysis_regression.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/04b_analysis_PH.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/04c_analysis_PH_severity.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/05a_analysis_regressionOutput.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/05a_ii_analyse_rate_differences.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/05b_analyse_severity.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/05c_analysis_regressionInteractions.R")) ; rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/05e_full_regression_tables.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/06_regressionethnicity.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/06b_analyse_ethnicityOutput.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/07_analyse_ghosts_regressions.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/07b_analyse_ghostsOutput.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/08_analyse_ghosts_regressions_3yrs.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/08b_analyse_ghostsOutput_3yrs.R"));rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/09_summarise_sensitivityanalyses.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/analysis/10_analysisPH_t_v2.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
#source(here::here("code/analysis/11_predictive_models.R")); rm(list=ls()); source(here::here("../../.Rprofile"))

## supplementary analsyes
source(here::here("code/supplementary/linked_data_availability.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
source(here::here("code/supplementary/ecz_sleep.R")); rm(list=ls()); source(here::here("../../.Rprofile"))
